{{- if .Values.enabled -}}
apiVersion: v1
data:
  .dockerconfigjson: <docker>
kind: Secret
metadata:
  name: public-web-registry-secret
  annotations:
    avp.kubernetes.io/path: {{ .Values.dockerAvp }}
type: kubernetes.io/dockerconfigjson
{{- end }}

